server:
  port: 8080

spring:
  application:
    name: palaver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/palaver
          jwk-set-uri: http://localhost:9090/auth/realms/palaver/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: login-app
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
